# Generated by Django 4.0 on 2022-01-20 15:57

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200, null=True, verbose_name='Вопросы')),
                ('answer', models.TextField(null=True, verbose_name='Ответ')),
            ],
            options={
                'verbose_name_plural': 'Часто задаваемые вопросы',
            },
        ),
        migrations.CreateModel(
            name='Help_questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, null=True, verbose_name='Имя')),
                ('email', models.CharField(max_length=250, null=True, verbose_name='email')),
                ('subject', models.CharField(max_length=250, null=True, verbose_name='Тема')),
                ('text', models.TextField(null=True, verbose_name='Текст')),
                ('create_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Отправлено')),
            ],
            options={
                'verbose_name': 'Вопросы от поситителей',
                'verbose_name_plural': 'Вопросы от поситителей',
            },
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True, verbose_name='Название сайта')),
                ('logo', models.ImageField(null=True, upload_to='logo', verbose_name='Логотип')),
                ('keywords', models.CharField(max_length=200, null=True, verbose_name='Ключевые слова')),
                ('description', models.TextField(null=True, verbose_name='Описание сайта')),
                ('location', models.CharField(blank=True, help_text='Мы находимся по адресу ул.Ленина 232', max_length=100, null=True, verbose_name='Локация')),
                ('phone', models.CharField(blank=True, max_length=100, null=True, verbose_name='Телефон')),
                ('email', models.CharField(blank=True, max_length=30, null=True, verbose_name='email')),
                ('facebook', models.CharField(blank=True, max_length=200, null=True, verbose_name='facebook')),
                ('instagram', models.CharField(blank=True, max_length=200, null=True, verbose_name='instagram')),
                ('twitter', models.CharField(blank=True, max_length=200, null=True, verbose_name='twitter')),
                ('youtube', models.CharField(blank=True, max_length=200, null=True, verbose_name='youtube')),
                ('about_page', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Основные настройки',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True, verbose_name='Имя')),
                ('image', models.ImageField(null=True, upload_to='team/', verbose_name='Фото')),
                ('rank', models.CharField(max_length=100, null=True, verbose_name='Звание в компании')),
                ('instagram', models.CharField(blank=True, max_length=100, null=True, verbose_name='instagram')),
            ],
            options={
                'verbose_name': 'Наша команда',
                'verbose_name_plural': 'Наша команда',
            },
        ),
        migrations.CreateModel(
            name='Theme_use',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme_use', models.CharField(max_length=100, null=True, verbose_name='Тема правил использования')),
                ('description_use', models.TextField(null=True, verbose_name='Описание использования')),
            ],
            options={
                'verbose_name_plural': 'Условия пользования',
            },
        ),
    ]
